### ISSUE TITLE
Main Restricted Master Selection

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/moontree#194]
### Describe The User Story

As a User I want to select the main, restricted or master coin so that I can navigate to its specific holding page.

### Tasks For This Story

 - [x] #227
 - [x] #239

### Design Spec ###
[Main Restricted Master Selection](https://xd.adobe.com/view/6434d1f0-aab0-4bcc-b1cf-83fcc74af3ee-3167/)

**Comment by lastmeta** [comment]
Maybe we should discuss this one, I feel like there are edge cases we need to consider. What if I hold the admin token but, but not a main token? Then I can get in the admin page but admins don't have children...

So should I show the children of the main on the admin page as well as the main? Or only show the main page in the first place since the list is already filtered to assets you hold the Admin token for...

If we do that the only options you'd ever see here are Admin, Restricted and Qualifier (I assume, can you manage a qualifier?) Anyway, we can talk about it Thursday.

**Comment by lastmeta** [comment]
basically the admin page plus sub stuff is the way we should go

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Nav Drawer](https://github.com/moontreeapp/moontree/issues/280)
