### ISSUE TITLE
Update Buttons to Figma

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#341]
### Describe The Task

- Remove Icons from buttons. 
- Update button height. 
- Update button disabled color.

### Additional Context

We recently changed the look of minor elements throughout the app. These need to be updated to the latest designs.

**Comment by Brock-Wood** [comment]
While working on this, I realized that the button sizing issue is a larger issue with dynamic sizing. This is probably because we need to not hard code sizes, but rather make them relative to screen size. This will require more research and can be a different task as it affects multiple components and features.
