### ISSUE TITLE
Integrate Splash Screen

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/moontree#389]
### Describe The Task

Load the splash screen on startup of the app.

### Additional Context

This should be done ideally while the app is grabbing data on startup. However, this currently does not work well; it makes the animation glitchy.

For MVP we can show the splash screen and then show the user the home page with a placeholder while the app grabs data.

**Comment by lastmeta** [comment]
it looks like there is a splash screen capability native under flutter
https://developer.android.com/topic/performance/vitals/launch-time#themed
https://docs.flutter.dev/development/ui/advanced/splash-screen
but I don't think that helps because it probably doesn't support lottie files out of the box

this tutorial is probably how I'd initially attempt it
https://www.youtube.com/watch?v=XXISgdYHdYw

though I found a few splash screen packages. this one does not support animations:
https://pub.dev/packages/flutter_native_splash
I'm not sure if this one does, but I doubt it, but worth looking into
https://pub.dev/packages/splashscreen

then of course there's stackoverflow, these should give some ideas about how others handle it
https://stackoverflow.com/questions/43879103/adding-a-splash-screen-to-flutter-apps
https://stackoverflow.com/questions/54575622/splash-screen-implementation-in-flutter
https://stackoverflow.com/questions/70694215/how-to-insert-flutter-splash-screen-before-this-sign-up-page-i-think-im-missin
https://stackoverflow.com/questions/68898936/splashscreen-before-materialapp-with-drawer
https://stackoverflow.com/questions/70661874/splash-screen-with-auto-route

this might be the most helpful looks like our structure with the materialapp builder
https://bettercoding.dev/flutter/initialization-splash/
https://stackoverflow.com/questions/52011367/dart-animating-materialapp-home-screen
https://stackoverflow.com/questions/59494674/flutter-splash-screens-the-right-way

maybe we could leverage firebase for this
https://stackoverflow.com/questions/53362149/materialapp-builder-customization-for-specific-page
