### ISSUE TITLE
[raven_front] fix transaction screen

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#5]
### Describe The Task

right now we show ever vout, we should instead show the result of multiple vouts. this mainly means filtering and adding some info to the one that was chosen:

example:
sending 6 to someone, consuming 10, return 4,

I should see sent 6 and that's it.

**Comment by lastmeta** [comment]
for each Vin and Vout we make a transaction record that looks like this
```
transactionRecord(
out: false
fromAddress: 
toAddress: mia15mxui5RVc1tBisLLrKFojNaiZUtsiW 
value: 4630145985500 
height: null 
formattedDatetime: in mempool 
amount: 0 
security: Security(symbol: RVN, securityType: SecurityType.Crypto) 
transactionId: b13feb18ae0b66f47e1606230b0a70de7d40ab52fbfc5626488136fbaa668b34 
voutId: b13feb18ae0b66f47e1606230b0a70de7d40ab52fbfc5626488136fbaa668b34:0 
vinId: null)
```
Then we display each one of these in the transaction list. When it comes to the transaction page we take the transaction id from this and look up the data and display it. 

What we should do instead is aggregate all information we need to a transaction record and display the result of that.

for example, here we have 2 transaction records where we sent 46k rvn to ourselves. these shows up as two as separate line items, then basically showing the same result of both in each transaction screen:
```
TransactionRecord(
  out: true,
  fromAddress: '',
  toAddress: 'mzSED3enx8mPaaDobDxzaBaKpySNfpUxdE',
  value: 4630146195600,
  height: null,
  formattedDatetime: 'in mempool',
  amount: 0,
  security: Security(symbol: 'RVN', securityType: SecurityType.Crypto),
  transactionId: 'b13feb18ae0b66f47e1606230b0a70de7d40ab52fbfc5626488136fbaa668b34',
  voutId: null,
  vinId: '0cfbcdcd00c628ff419b8fd0f39963b7875e6146ed56b27a3494ae1095f1d151'),
TransactionRecord(
  out: false,
  fromAddress: '',
  toAddress: 'mia15mxui5RVc1tBisLLrKFojNaiZUtsiW',
  value: 4630145985500,
  height: null,
  formattedDatetime: 'in mempool',
  amount: 0,
  security: Security(symbol: 'RVN', securityType: SecurityType.Crypto,
  transactionId: 'b13feb18ae0b66f47e1606230b0a70de7d40ab52fbfc5626488136fbaa668b34',
  voutId: 'b13feb18ae0b66f47e1606230b0a70de7d40ab52fbfc5626488136fbaa668b34:0',
  vinId: null)
```
![image](https://user-images.githubusercontent.com/5642485/147126222-82859876-ceef-4d2c-a1b0-7b7387abc9ef.png)

Instead we should show one line item and all the needed info in the transaction screen. The line item should say "out .002101" which was the transaction fee.  perhaps we can add something in the transaction screen like "x sent back to yourself, with a transaction fee of y" but instead of implementing that part right now, we'll stick to the simplest form.
