### ISSUE TITLE
False loading of holdings

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#531]
### Describe The Bug

A loading list shimmer is being shown quickly before the default wallet placeholder. 
Splash Screen -> Shimmer List -> Wallet  Placeholder

### To Reproduce

1. Download fresh app
2. Start app
3. View bug on wallet home screen

### Expected Behavior

Splash Screen -> Wallet Placeholder

### Screenshots

![Screenshot_20220504-101717_Squid](https://user-images.githubusercontent.com/9276931/166727898-f86892fe-459d-45f8-b904-2bdcaf4f12dc.jpg)

### Tasks For This Bug

 - [ ] #

**Comment by lastmeta** [comment]
for this we'll to add the ability to differentiate between two cases: 1. auto-generated wallet (which we know is empty) 2. imported wallet, (which we think isn't empty).

right now the default case is made for the imported case (2): show loading.

So we'll need to say, that's the default case, and when we auto-generate a wallet we'll differentiate that case and just immediately display the empty wallet message while it would otherwise display the loading one row (because it doesn't know).

**Comment by lastmeta** [comment]
post mvp
