### ISSUE TITLE
Loading Lottie Glitchy 

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#532]
### Describe The Bug

When sending, the loading lottie is glitchy and does not run smoothly.

### To Reproduce

Send

### Expected Behavior

Smooth Lottie animation

### Screenshots

![Screenshot_20220504-101725_Squid](https://user-images.githubusercontent.com/9276931/166728352-ab4f7fd5-e762-4e74-a993-120987fcf928.jpg)

### Tasks For This Bug

 - [ ] #

**Comment by lastmeta** [comment]
we'll send it after we run the lottie file a couple times. we'll also add in code to the send waiter to say, if you're still in the newLeaderProcess (import download process) wait until you're done because we have to wait for the utxos to be downloaded in order to actually create the transaction... that might merit it's own ticket..

**Comment by lastmeta** [comment]
this is glitchy on import too.
