### ISSUE TITLE
Grab or Generate Asset Icon

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/moontree#86]
### Describe The Task

We need to see the icon on the holding screen and other place so, in the back end create a process that grabs or generates the asset icon and saves it where it can be retrieved upon demand.

### Additional Context

[Holdings](https://github.com/moontreeapp/moontree/issues/78)

**Comment by Brock-Wood** [comment]
@lastmeta Here is the place to grab the identicons from:

[Identicon Docs](https://avatars.dicebear.com/styles/identicon)

**Comment by lastmeta** [comment]
@WhaleStreet do you mind if we use something like this https://pub.dev/packages/jdenticon_dart rather than the identicon api? having the phone generate the svg is more ideal I think because we can generate it on the fly each time, no need to save and load images (or hit an external api constantly) and no need to validate the data from the api.
Dart packages
jdenticon_dart | Dart Package
This is the Dart/Flutter implementation of the Jdenticon project. Jdenticon is a quick and easy to use library for generating highly recognizable identicons using SVG.
Image
WhaleStreet — Today at 1:39 PM
Looks good! 
@meta stack
